server:
  rootPath: /fpl-wrapper
swagger:
  resourcePackage: resources
  title: FPLWrapper
  version: 0.2.0
  description: A user-friendly API for the Fantasy Premier League online game.
  contact: Yll Kelani
  contactEmail: yll.kelani@hotmail.co.uk
